export const actions ={

    UPDATE_AVATAR: 'user/setImageAvatar',
    LOGIN_GOOGLE: "LOGIN_GOOGLE",
    LOGIN_MAIL: "LOGIN_MAIL",
    UPDATE_DATA_USER:"UPDATE_DATA_USER",
    UPATE_DATA_MAINTENANCE:"UPATE_DATA_MAINTENANCE"

}
